//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICIBaamInterface")]
public interface ICIBaamInterface
{

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICIBaamInterface/GetValue", ReplyAction = "http://tempuri.org/ICIBaamInterface/GetValueResponse")]
	string GetValue(int commandID);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICIBaamInterface/GetValue", ReplyAction = "http://tempuri.org/ICIBaamInterface/GetValueResponse")]
	System.Threading.Tasks.Task<string> GetValueAsync(int commandID);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICIBaamInterface/SetValue", ReplyAction = "http://tempuri.org/ICIBaamInterface/SetValueResponse")]
	int SetValue(int commandID, string commandValue);

	[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICIBaamInterface/SetValue", ReplyAction = "http://tempuri.org/ICIBaamInterface/SetValueResponse")]
	System.Threading.Tasks.Task<int> SetValueAsync(int commandID, string commandValue);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICIBaamInterfaceChannel : ICIBaamInterface, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CIBaamInterfaceClient : System.ServiceModel.ClientBase<ICIBaamInterface>, ICIBaamInterface
{

	public CIBaamInterfaceClient()
	{
	}

	public CIBaamInterfaceClient(string endpointConfigurationName) :
			base(endpointConfigurationName)
	{
	}

	public CIBaamInterfaceClient(string endpointConfigurationName, string remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
	{
	}

	public CIBaamInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
	{
	}

	public CIBaamInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
			base(binding, remoteAddress)
	{
	}

	public string GetValue(int commandID)
	{
		return base.Channel.GetValue(commandID);
	}

	public System.Threading.Tasks.Task<string> GetValueAsync(int commandID)
	{
		return base.Channel.GetValueAsync(commandID);
	}

	public int SetValue(int commandID, string commandValue)
	{
		return base.Channel.SetValue(commandID, commandValue);
	}

	public System.Threading.Tasks.Task<int> SetValueAsync(int commandID, string commandValue)
	{
		return base.Channel.SetValueAsync(commandID, commandValue);
	}
}
